development:
  adapter: mysql2
  encoding: utf8
  database: meet_doc_dev
  pool: 5
  username: root
  password: 
  port: 3306

test:
  adapter: mysql2
  encoding: utf8
  database: meet_doc_test
  pool: 5
  username: root
  password: 
  port: 3306

production:
  adapter: mysql2
  encoding: utf8
  database: meet_doc_prod
  pool: 5
  username: root
  password: 
  port: 3306
